version: 2

sources:
  - name: src
    database: assessment
    schema: jaffle
    tables:
      - name: customers
      - name: items
      - name: orders
      - name: products
      - name: stores
      - name: supplies